repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: tofu-fmt
        name: tofu fmt
        entry: pixi run tf-fmt
        language: system
        pass_filenames: false
      - id: tofu-validate
        name: tofu validate
        entry: pixi run tf-validate
        language: system
        pass_filenames: false
