[project]
name = "gcp-work"
version = "0.1.0"
description = "GCP infrastructure tooling"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64"]

[dependencies]
opentofu = ">=1.6.0"
python = "3.11.*"
pre-commit = ">=3.6,<4.0"

[tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run --all-files"
tf-fmt = "tofu fmt -check -diff"
tf-validate = "tofu validate"
