output "ingress_route_name" {
  description = "Name of the Traefik IngressRoute resource."
  value       = kubernetes_manifest.ingress_route.manifest["metadata"]["name"]
}

output "forward_auth_middleware_name" {
  description = "Name of the forward-auth middleware (if created or referenced)."
  value = (
    var.proxy_service_name != null &&
    var.root_route_backend == "upstream" &&
    (var.forward_auth_middleware_name != null || var.create_forward_auth_middleware)
  ) ? local.forward_auth_name : null
}

output "host" {
  description = "Hostname protected by this IngressRoute."
  value       = var.host
}

output "header_middlewares" {
  description = "Header middlewares generated by this module."
  value = [
    for _, hm in local.header_middlewares_map : {
      name      = hm.name
      namespace = coalesce(hm.namespace, var.namespace)
    }
  ]
}
